<?php
 // module/Album/view/album/album/add.phtml:

 $title = 'Add new rol';
 $this->headTitle($title);
 ?>


 <h1><?php echo $this->titulo;?></h1>

<table style="width:400px; text-align:left">
   <tr>
        <th>ID</th>
	    <th>rol_name</th>
	    <th>description</th>
    </tr>
	<?php foreach ($this->datos as $dato){?>
	     <tr style="background-color:<?php echo $this->cycle(array("#F0F0F0","#FFFFFF"))->next()?>">
		 <td><?php  echo $dato["id"] ?></td>
		 <td><?php  echo $dato["rol_name"] ?></td>
		 <td><?php  echo $dato["description"] ?></td>
		 <td>
		    <a href="<?php  echo $this->basePath() ?>/users/roles/verRol/<?php echo $dato["id"]?>">ver</a>
		</td>
	     </tr>
	<?php }?>
	<?php
	$this->cycle()->assign(array("#F0F0F0","#FFFFFF"));
	$this->cycle()->prev();
	?>
</table>
		