<?php
 // module/Album/view/album/album/add.phtml:

 $title = 'Add new rol';
 $this->headTitle($title);
 ?>
<h1><?php echo $this->titulo;?></h1>
<?php
$form->setAttribute('action',$this->url('usuario',array('action'=>'add')));
$from->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('rol_name'));
 echo $this->formRow($form->get('description'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 ?>
