<?php
 // module/Album/view/album/album/index.phtml:
 $title = 'My rol';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
<a class="btn btn-success" name="button2" type="button" 
    value="ALERTA" href="<?php  echo $this->basePath() ?>/users/users/registroRol">Create </a>			
</p>
 
<table style="width:400px; text-align:left">
   <tr>
        <th>ID</th>
        <th>Rol_Name</th>
	    <th>Description</th>
        
    </tr>
	<?php foreach ($this->datos as $dato){?>
	     <tr style="background-color:<?php echo $this->cycle(array("#FFDAB9","#FFFFFF"))->next()?>">
		 <td><?php echo $dato["id"] ?></td>
		 <td><?php echo $dato["rol_name"] ?></td>
		 <td><?php echo $dato["description"] ?></td>
    
         <td><a class="btn btn-primary"  name="button2" type="button" 
                             value="ALERTA" href="<?php echo $this->basePath() ?>/users/roles/edit/<?php echo $dato["id"]?>">Edit</a></td>
                             
         <td><a class="btn btn-danger" id="1" name="button2" type="button" 
                            value="ALERTA" href="<?php echo $this->basePath() ?>/users/roles/delete/<?php echo $dato["id"]?>">Deleite</a></td>
							
	           
		  </tr>
	<?php }?> 
	<?php
	$this->cycle()->assign(array("#FFDAB9","#FFFFFF"));
	$this->cycle()->prev();
	?>
</table>




