
<?php
 
 $title = 'My rol';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
    <a class="btn btn-info"  href="<?php  echo $this->url('users/shop', array('controller'=>'roles','action'=>'addRoles'));?>">Create </a>          
 </p>
 

<table class="table">
   <tr>
        <th>ID</th>
        <th>Rol_Name</th>
        <th>Description</th>
        
    </tr>
    <?php foreach ($roles as $roles): ?>
         <tr>
    <td> <?php echo $this->escapeHtml($roles->rolId);?></td>
     <td> <?php echo $this->escapeHtml($roles->rolName);?></td>
     <td><?php echo $this->escapeHtml($roles->description);?></td>
     <td>
        
      <?php $url = $this->url('users/shop', array(
                'controller' => 'roles',
                'action' => 'deleteRoles',
                'rolId'     => $roles->rolId,
            ));
            ?>
             <form action="<?php echo $url; ?>" method="post">
                <a class="btn btn-success" href="<?php echo $this->url('users/shop',
             array('controller' => 'roles', 'action'=>'updateRoles', 'id' => $roles->rolId));?>">Modificar</a>
             <input type="hidden" name="rol_id" value="<?php echo (int) $roles->rolId; ?>" />
                 <input class="btn btn-danger" type="submit" value="Eliminar" onclick="return confirm('¿Estás seguro que lo deseas eliminar?')" />
             </form>
              </td>
 </tr>
 <?php endforeach; ?>
 </table>

