<h1> Usuarios </h1>

	
<h1>
<?php print_r($this->titulo);?>
</h1>


<?php
$form = $this->form;
$form->prepare();


$form->setAttributes(array(
   'action'=> $this->url.'/usuarios/usuarios/index',
	'method'=> 'post'
	));
$formLabel=$this->plugin('formLabel');
 echo $this->form()->openTag($form);
?>


<?php
if(!empty($this->id))
{
	?>
          <p  class="close" data-dismiss='alert("confirme para realizar la modificacion")'  value="ALERTA" style="color:cyan;"> El registro se ingreso</p>
      
        <p>
           <td><a  class="btn btn-success"  name="button" type="button" onclick='confirm("antes de visualisar la lista de registros!!\n\Esta seguro que no decea realizar algun otro registro.")' 
                       value="ALERTA"  href="<?php  echo $this->basePath() ?>/usuario/index/index">ver</a></td>                             
        </p>
<?php
}
?>


<div class="form_element">

<?php
$email= $form->get('email');
echo $formLabel->openTag().$email->getOption('label')." ";
echo $this->formElementErrors($email);
echo $formLabel->closeTag();
echo $this->formInput($email);
?>
</div>

<div class="form_element">

<?php
$password= $form->get('password');
echo $formLabel->openTag().$password->getOption('label')." ";
echo $this->formElementErrors($password);
echo $formLabel->closeTag();
echo $this->formInput($password);
?>
</div>

<?php echo  $this->formElement($form->get('zend')); ?>

<?php echo $this->form()->closeTag()?>