<h1><?php print_r($this->titulo)?> </h1>
<?php
$form= $this->form;
$form->prepare();

//Manda los atributos por el metodo POST
$form->setAttributes(array(
	'action' =>$this->url.'/products/add-Category',
	'method' => 'post'
));

$formLabel = $this->plugin('formLabel');

echo $this->form()->openTag($form);

?>


<a href="<?php echo $this->basePath() ?>/products">Volver Atrás</a>

<div class="form_element">
<?php
//Caja de texto para el nombre de la categoria 
	$name = $form->get('category_name');
	echo $formLabel->openTag() . $name->getOption('label'). " ";
	echo $this->formInput($name);;
	echo $formLabel->closeTag();
?>
</div>
<hr />
<div class="form_element">

<?php
//Campo de texto para la descripcion de la categoria
	$desc = $form->get('description');
	echo $formLabel->openTag() . $desc->getOption('label'). " ";
	echo $this->formInput($desc);
	echo $formLabel->closeTag();
?>
</div>
<hr />

<?php echo $this->formElement($form->get('send')) ?>
<?php echo $this->form()->closeTag() ?>