<?php

 $title = 'Categorias';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <br/>
 <br/>
 <p>
     <a class="btn btn-info" href="<?php echo $this->url('products/shop', array('controller' => 'category', 'action'=>'addCategory'));?>">Nuevo</a>
     
 </p>

 <table class="table">
 <tr>
     <th>ID</th>
     <th>Nombre</th>
     <th>Descripción</th>
 </tr>
 <?php foreach ($categorys as $category) : ?>
 <tr>
     <td> <?php echo $this->escapeHtml($category->categoryId);?></td>
     <td><?php echo $this->escapeHtml($category->categoryName);?></td>
     <td><?php echo $this->escapeHtml($category->description);?></td>
     <td>
             <?php $url = $this->url('products/shop', array(
                'controller' => 'category',
                'action' => 'deleteCategory',
                'categoryId'     => $category->categoryId,
            ));
            ?>
            <form action="<?php echo $url; ?>" method="post">
                <a class="btn btn-success" href="<?php echo $this->url('products/shop',
             array('controller' => 'category', 'action'=>'updateCategory', 'id' => $category->categoryId));?>">Modificar</a>
                 <input type="hidden" name="category_id" value="<?php echo (int) $category->categoryId; ?>" />
                 <input class="btn btn-danger" type="submit" value="Eliminar" onclick="return confirm('¿Estás seguro que lo deseas eliminar?')" />
             </form>
             
        
     </td>
 </tr>
 <?php endforeach; ?>
 </table>