<?php

 // module/Album/view/album/album/edit.phtml:

 $title = 'Editar Categoria';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'products/shop',
     array(
     	'controller' => 'category',
        'action' => 'updateCategory',
        'id'     => $this->id,
     )
 ));
// echo print_r($form->get('category_name'));
 //exit;
$form->prepare();
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('category_id'));
 echo "<br/>";
 echo $this->formRow($this->form->get('category_name'));
 echo "<br/>";
 echo $this->formRow($form->get('description'));
 echo "<br/>";
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 ?>
