<?php
 // module/Album/view/album/album/index.phtml:
 $title = 'Agregar Producto';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 
 <?php
 $form->setAttribute('action', $this->url('products/shop', array('controller' => 'products', 'action'=>'addProduct')));
 $form->prepare();
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('product_id'));
 echo "<br/>";
 echo $this->formRow($form->get('category_id'));
 echo "<br/>";
 echo $this->formRow($form->get('description'));
 echo "<br/>";
 echo $this->formRow($form->get('barcode'));
 echo "<br/>";
 echo $this->formRow($form->get('image'));
 echo "<br/>";
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 