<?php

 $title = 'Usuarios';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a class="btn btn-info" href="<?php echo $this->url('users/shop', array('controller' => 'users', 'action'=>'addUser'));?>">Nuevo</a>
 </p>


 <table class="table">
 <tr>
    <th>Id</th>
    <th>Rol</th>
     <th>Correo Electronico</th>
     
     
 </tr>
 <?php foreach ($users as $user) : ?>
 <tr>
    <td><?php echo $this->escapeHtml($user['user_id']);?></td>
     <td><?php echo $this->escapeHtml($user['roles']);?></td>
     <td><?php echo $this->escapeHtml($user['email']);?></td>
     
     
     <td>
           <?php $url = $this->url('users/shop', array(
                'controller' => 'users',
                'action' => 'deleteUser',
                'userId'     => $user['user_id'],
            ));
            ?>
            <form action="<?php echo $url; ?>" method="post">
                <a class="btn btn-success" href="<?php echo $this->url('users/shop',
             array('controller' => 'users', 'action'=>'updateUser', 'id' => $user['user_id']));?>">Modificar</a>
                 <input type="hidden" name="user_id" value="<?php echo (int) $user['user_id']; ?>" />
                 <input class="btn btn-danger" type="submit" value="Eliminar" onclick="return confirm('¿Estás seguro que lo deseas eliminar?')" />
             </form>
     
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
