<?php
  
 $title = 'Notas de Venta';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
  <br/>
  <br/>
  <br/>
 

  
 <table class="table-bordered" width="1150">
 <tr>
     <th>ID</th>
     <th>Articulo</th>
	 <th>Cantidad</th>
     <th>Descripción</th>
     <th>Precio</th>
 </tr>
 </table >
 
  <br/>
  <br/>
  <br/>
  <br/>
  <br/>
  <br/>
  <br/>
  <br/>
 
 <table  class="table-bordered" width="1150">
 <tr>

     <td>Observaciones</td>

     <td>Subtotal:</td>

    <td><input type="number" class="form-control" id="usr">
	</td>
	 <td>Cantidad</td>
	 <td><input type="number" class="form-control" id="usr"></td>
	 <td>IVA</td>
	 <td><input type="number" class="form-control" id="usr"></td>

  </tr>

  <tr>

    <td><textarea class="form-control" rows="3" id="comment"></textarea>
	</td>

    <td>Total Venta</td>

    <td><input type="number" class="form-control" id="usr"></td>
    <td>Recibido</td>
	<td><input type="number" class="form-control" id="usr"></td>
	<td>Cambio</td>
	<td><input type="number" class="form-control" id="usr"></td>
  </tr>

</table>